- Dockerfile
- README.md
+ compiles par2 multicore as per link in updated Sabnzbd [readme](https://forums.sabnzbd.org/viewtopic.php?f=16&t=18793#p99702)
> compile par2 multicore

- Dockerfile
- README.md
+ whilst current latest is a "stable" version taking opportunity to make switch \
to latest/master being nobetas apt repo for sabnzbd app.
> switch to nobetas repo in master branch

- Dockerfile
- README.md
- list
+ bump to version 2.0
+ add par2-tbb from sab addons ppa
+ add sabyenc from sab addons ppa
+ closes #26
> bump to version 2.0

- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
- Jenkinsfile
- README.md
- jenkins-vars.yml
- readme-vars.yml
This has been loop tested locally, the end image actually comes out smaller than our old one due to reductions in bionic base. 
Reference Issues and PRs:
https://github.com/linuxserver/docker-sabnzbd/issues/44
https://github.com/linuxserver/docker-sabnzbd/issues/34
https://github.com/linuxserver/docker-sabnzbd/pull/45
> Rebase to bionic add some common python deps

- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
- Jenkinsfile
- README.md
- jenkins-vars.yml
- readme-vars.yml
Closes #74 
Also need to update the jenkins trigger once merged: https://ci.linuxserver.io/job/External-Triggers/job/sabnzbd-unstable-external-trigger/
> switch to ppa:jcfp/ppa for unstable tag

- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
- Jenkinsfile
- README.md
- jenkins-vars.yml
- readme-vars.yml
- root/etc/services.d/sabnzbd/run
Once merged, the Jenkins trigger needs to be updated
> run from source with python3 instead of ppa

- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
When installing pip we need to use --no-cache-dir
Will solve issue #94 
By not creating a /config/.cache/pip folder
> do not use pip3 cache when install pip by adding --no-cache-dir

- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
- README.md
- readme-vars.yml
> add python3-setuptools

- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
- README.md
- readme-vars.yml
- root/etc/services.d/sabnzbd/run
* Don't enforce binding to ipv4 (fixes #82, `HAS_IPV6` var might have to be set to `false`)
* Don't set port in startup (fixes #90)
Did a download on aarch64
Supersedes, thus closes #100
> Bump to focal

- readme-vars.yml
> Add unstable rebase changelog

- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
- readme-vars.yml
> Build unrar from source

- .github/ISSUE_TEMPLATE/issue.bug.md
- .github/ISSUE_TEMPLATE/issue.feature.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/greetings.yml
- Jenkinsfile
- README.md
- readme-vars.yml
- root/etc/cont-init.d/99-deprecation
> Deprecate Alpine Branch

- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
- readme-vars.yml
Closes https://github.com/linuxserver/docker-sabnzbd/issues/128
> Add nzb-notify

- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
- readme-vars.yml
Closes https://github.com/linuxserver/docker-sabnzbd/issues/128
> Add nzb-notify (unstable branch)

- readme-vars.yml
Re https://github.com/linuxserver/docker-sabnzbd/pull/137
> Add nightly tag

- root/etc/s6-overlay/s6-rc.d/svc-sabnzbd/run
> Use localhost for readiness check

- root/etc/s6-overlay/s6-rc.d/svc-sabnzbd/run
> Use localhost for readiness checks

- root/etc/s6-overlay/s6-rc.d/init-sabnzbd-config/run
> Use lsiown for init (nightly)

- root/etc/s6-overlay/s6-rc.d/init-sabnzbd-config/run
> Use lsiown for init (unstable)

- root/etc/s6-overlay/s6-rc.d/init-sabnzbd-config/run
> Use lsiown for init (master)

- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
- README.md
- readme-vars.yml
> Rebase nightly to edge for py 3.11

- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
- root/etc/s6-overlay/s6-rc.d/init-sabnzbd-config/run
- root/etc/s6-overlay/s6-rc.d/svc-sabnzbd/run
See https://peps.python.org/pep-0668/
> Delete EXTERNALLY-MANAGED for py install.

- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
- README.md
- readme-vars.yml
- root/etc/s6-overlay/s6-rc.d/init-sabnzbd-config/run
- root/etc/s6-overlay/s6-rc.d/svc-sabnzbd/run
> Rebase unstable to 3.17

- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
- README.md
- readme-vars.yml
- root/etc/s6-overlay/s6-rc.d/init-sabnzbd-config/run
- root/etc/s6-overlay/s6-rc.d/svc-sabnzbd/run
> Rebase master to 3.17

- root/etc/s6-overlay/s6-rc.d/svc-sabnzbd/data/check
- root/etc/s6-overlay/s6-rc.d/svc-sabnzbd/run
> Query sab properly for readiness check

- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
- README.md
- readme-vars.yml
> Switch from p7zip to 7zip, bump unrar to 6.2.6 - nightly

- Dockerfile
- Dockerfile.aarch64
- readme-vars.yml
> Bump unrar to 6.2.10 (unstable)

- Dockerfile
- Dockerfile.aarch64
- README.md
- readme-vars.yml
> Switch to par2cmdline-turbo (unstable)

- Dockerfile
- Dockerfile.aarch64
- README.md
- readme-vars.yml
> Switch to par2cmdline-turbo (master)

- Dockerfile
- Dockerfile.aarch64
- readme-vars.yml
> Build translations, remove libgomp (unstable)

- Dockerfile
- Dockerfile.aarch64
- readme-vars.yml
> Build translations, remove libgomp (master)

- Dockerfile
- Dockerfile.aarch64
- readme-vars.yml
Just doing nightly for now, need to give a longer migration time before we look at unstable/master
> Remove nzbnotify

- Dockerfile
- Dockerfile.aarch64
- Jenkinsfile
- README.md
- jenkins-vars.yml
- readme-vars.yml
> Rebase to 3.20 (unstable), remove nzbnotify

- Dockerfile
- Dockerfile.aarch64
- readme-vars.yml
- root/etc/s6-overlay/s6-rc.d/init-sabnzbd-config/run
> Conditional chowns (master)

- Dockerfile
- Dockerfile.aarch64
- readme-vars.yml
- root/etc/s6-overlay/s6-rc.d/init-sabnzbd-config/run
> Conditional chowns (nightly)

- readme-vars.yml
> Remove ambiguity around download paths (nightly)

- readme-vars.yml
> Remove ambiguity around download paths (master)

- readme-vars.yml
> Remove ambiguity around download paths (unstable)

- Jenkinsfile
- jenkins-vars.yml
- root/etc/s6-overlay/s6-rc.d/svc-sabnzbd/run
> Make checks consistent between init and svc

- README.md
- readme-vars.yml
> Fix silly typo

- Dockerfile
- Dockerfile.aarch64
- README.md
- readme-vars.yml
> Rebase to 3.22
